### PR TITLE
Display text under info QR code

### PR DESCRIPTION
**Pull request by n-vr**
## What does this change
- The text 'Scan voor info' is now displayed under the info QR-code that is shown after provisioning.
- A new class 'Screen' was created, which can control an eInk screen. It can clear the screen and display a QR, with or without text. If the text is changed, the text will resize to fit under a QR code.
- We use LovyanGFX directly, not through twomes_provisioning_tools.
  - [x] This is changed in the README.

## Testing
These changes can be tested by using the [co2 monitor firmware repository](https://github.com/energietransitie/twutility-twomes-co2-bt-occupancy-monitor-firmware/tree/use-generic-library) on the [`use-generic-library`](https://github.com/energietransitie/twutility-twomes-co2-bt-occupancy-monitor-firmware/tree/use-generic-library) branch.
1. Make the following change to the `platformio.ini` file.
    ```diff
    - https://github.com/energietransitie/twomes-generic-esp-firmware
    + https://github.com/energietransitie/twomes-generic-esp-firmware#screen-improvements
    ```
2. Compile the firmware and flash it onto a device.

## Trello card(s)
- Add informational QR-code pointing to `https://edu.nl/4pujw` after provisioning: https://trello.com/c/dE7AePCQ

### CODE REVIEW

**Review by henriterhofte — CHANGES_REQUESTED** [review]
We're no longer using the Twomes provisioning tools sector, but still use the code. In that case, please add in the README.MD under the section under "Thanks also go to":
* Stijn Wingens · [@stijnwingens](https://github.com/stijnwingens)
* Jorrin Kievit · [@JorrinKievit](https://github.com/JorrinKievit)

**Comment by n-vr** [comment]
> We're no longer using the Twomes provisioning tools sector, but still use the code. In that case, please add in the README.MD under the section under "Thanks also go to":
> * Stijn Wingens · [@stijnwingens](https://github.com/stijnwingens)
> * Jorrin Kievit · [@JorrinKievit](https://github.com/JorrinKievit)

@henriterhofte what code are you referring to?

**Comment by henriterhofte** [comment]
> > We're no longer using the Twomes provisioning tools sector, but still use the code. In that case, please add in the README.MD under the section under "Thanks also go to":
> > 
> > * Stijn Wingens · [@stijnwingens](https://github.com/stijnwingens)
> > * Jorrin Kievit · [@JorrinKievit](https://github.com/JorrinKievit)
> 
> @henriterhofte what code are you referring to?

The twomes provisioning tools repo (which can probably be deleted now). Stijn and Jorrit helped us figure out LovyanGFX so they deserve some credit in this repo instead.

**Comment by henriterhofte** [comment]
QR + text works, but image is not crystal clear. Perhaps screen draw/ refresh  now done differently??

**Comment by n-vr** [comment]
> > > We're no longer using the Twomes provisioning tools sector, but still use the code. In that case, please add in the README.MD under the section under "Thanks also go to":
> > > 
> > > * Stijn Wingens · [@stijnwingens](https://github.com/stijnwingens)
> > > * Jorrin Kievit · [@JorrinKievit](https://github.com/JorrinKievit)
> > 
> > @henriterhofte what code are you referring to?
> 
> The twomes provisioning tools repo (which can probably be deleted now). Stijn and Jorrit helped us figure out LovyanGFX so they deserve some credit in this repo instead.

@henriterhofte Now I get it, thank you for clarifying. Yes, I agree.

**Review by henriterhofte — APPROVED** [review]

**Pull request merged**
